// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"github.com/moyu-x/infinite-synthesis/pkg/config"
	"github.com/moyu-x/infinite-synthesis/pkg/gorm"
	"github.com/moyu-x/infinite-synthesis/pkg/log"
	"github.com/moyu-x/infinite-synthesis/pkg/server/app"
	"github.com/moyu-x/infinite-synthesis/pkg/server/http"
)

// Injectors from wire.go:

func initServer(c *config.Bootstrap) *app.App {
	logger := log.NewLogger(c)
	server := http.NewServer(c, logger)
	appApp := app.NewApp(server)
	return appApp
}

// wire.go:

var pkgProviderSet = wire.NewSet(http.NewServer, app.NewApp, log.NewLogger, gorm.NewGORM)
