// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"github.com/moyu-x/infinite-synthesis/pkg/server/http"
)

// Injectors from wire.go:

func initServer() *http.Server {
	server := http.NewServer()
	return server
}

// wire.go:

var pkgProviderSet = wire.NewSet(http.NewServer)
